src/BPBusService/Controllers/BPBusStopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BPBusService.Models;

namespace BPBusService.Controllers
{
    /*  Birju Patel
     *  Student ID : 7120967
     *  9/20/2016
     * 
     *  BPBusStopController is a controller which manages the Index, Create, Edit, Delete and Details views 
     *  of the Bus Stops for the Bus Service apllication
    */
    public class BPBusStopController : Controller
    {
        private readonly BusServiceContext _context;
        public BPBusStopController(BusServiceContext context)
        {
            _context = context;    
        }

        // GET: BPBusStop
       //  The Index view gets called when the Bus Stops link is clicked and displays the Bus Stops with the 'GoingDowntown','Location' and 'LocationHash' fields
        public async Task<IActionResult> Index()
        {
            return View(await _context.BusStop.ToListAsync());
        }

        // GET: BPBusStop/Details/5
        // The Detials view gets called when the detials of a particular stop is opened 
        // It displays the BusStopNumber, GoingDowntown, Location and LocationHash
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var busStop = await _context.BusStop.SingleOrDefaultAsync(m => m.BusStopNumber == id);
            if (busStop == null)
            {
                return NotFound();
            }

            return View(busStop);
        }

        // GET: BPBusStop/Create
        // The Create view gets called when a new Bus Stop has to be created and allows the Bu Stop details to be entered
        public IActionResult Create()
        {
            return View();
        }

        // POST: BPBusStop/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        
        // This Create view gets called when detials about the new Bus Stop have been entered and the save button is clicked
        // The new Bus Stop and the details are added to the databse
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BusStopNumber,GoingDowntown,Location,LocationHash")] BusStop busStop)
        {
            if (ModelState.IsValid)
            {
                busStop.LocationHash = getHashValue(busStop.Location);
                
                _context.Add(busStop);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(busStop);
        }

        // GET: BPBusStop/Edit/5
        // The Edit view gets called when the details of a particular Bus Stop need to be changed

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var busStop = await _context.BusStop.SingleOrDefaultAsync(m => m.BusStopNumber == id);
            if (busStop == null)
            {
                return NotFound();
            }
            return View(busStop);
        }

        // POST: BPBusStop/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.

       // This Edit view gets called when the details of a bus stop have been edited and needs to be saved to the database
       // The details are passed through the paramater
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BusStopNumber,GoingDowntown,Location,LocationHash")] BusStop busStop)
        {
            if (id != busStop.BusStopNumber)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    busStop.LocationHash = getHashValue(busStop.Location);
                    _context.Update(busStop);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BusStopExists(busStop.BusStopNumber))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(busStop);
        }

        // GET: BPBusStop/Delete/5
        // This Delete view takes the Bus Stop number as the parameter and pulls up the details  awaiting for confirmation to delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var busStop = await _context.BusStop.SingleOrDefaultAsync(m => m.BusStopNumber == id);
            if (busStop == null)
            {
                return NotFound();
            }

            return View(busStop);
        }

        // POST: BPBusStop/Delete/5
        // This Delete view removes the record with the id passed through the parameter from the database and returns to the Index view
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var busStop = await _context.BusStop.SingleOrDefaultAsync(m => m.BusStopNumber == id);
            _context.BusStop.Remove(busStop);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        //show all routes using the stop given (if any)
        public  IActionResult RouteSelector(int busStopNumber = 0)
        {
            if (busStopNumber == 0)
            {
                TempData["message"] = "Please select a bus stop";
                return RedirectToAction("Index");
            }
            //ViewBag.busStopNumber = busStopNumber;
            var busStop = _context.BusStop.Where(x => x.BusStopNumber == busStopNumber).Include(x => x.Location);

            Response.Cookies.Append("busStopNumber", busStopNumber.ToString());
            
            

            var routeStops = _context.RouteStop.Where(x => x.BusStopNumber == busStopNumber).Include(x => x.BusRouteCodeNavigation);
            

            // If there are no routes using that stop, display a message to that effect
            if(routeStops.Count() <= 0)
            {
                TempData["message"] = "No routes uses stop " + busStopNumber;
                return RedirectToAction("Index");
            }

            //If only one route uses the stop, pass the RouteStopId to BPRouteSchedule controller's RouteStopSchedule Action
            if(routeStops.Count() == 1)
            {
                int routeStopId = routeStops.Select(x => x.RouteStopId).Single();
                return RedirectToAction("RouteStopSchedule", "BPRouteSchedule", new { routeStopId = routeStopId });
            }
            else
            {
                ViewBag.routeStopId = new SelectList(routeStops.Select(x => new { x.RouteStopId, x.BusRouteCodeNavigation.RouteName }).OrderBy(x => x.RouteName).ToList(), "routeStopId", "routeName");
            }

            return View(routeStops);
        }

        private bool BusStopExists(int id)
        {
            return _context.BusStop.Any(e => e.BusStopNumber == id);
        }

        // Hash Function that generates the hash key by adding up the byte value of each character in the string passed
        private int getHashValue(string location)
        {
          int hashValue = 0;
          for (int i=0; i < location.Length; i++)
            {
                hashValue += Convert.ToInt32(location.ElementAt(i));
            }
            return hashValue;
        }
    }
}

src/BPBusService/Controllers/BPDriverController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BPBusService.Models;
/*  Birju Patel
     *  Student ID : 7120967
     *  11/15/2016
     * 
     *  BPDriverController is a controller which manages the Index, Create, Edit, Delete and Details views 
     *  of the Drivers' details for the Bus Service apllication
    */
namespace BPBusService.Controllers
{
    public class BPDriverController : Controller
    {
        private readonly BusServiceContext _context;

        public BPDriverController(BusServiceContext context)
        {
            _context = context; 
        }



        // GET: BPDriver
        public async Task<IActionResult> Index()
        {
            var busServiceContext = _context.Driver.Include(d => d.ProvinceCodeNavigation).OrderBy(d => d.FullName);
            return View(await busServiceContext.ToListAsync());
        }

        // GET: BPDriver/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var driver = await _context.Driver.SingleOrDefaultAsync(m => m.DriverId == id);
            if (driver == null)
            {
                return NotFound();
            }

            return View(driver);
        }

        // GET: BPDriver/Create
        public IActionResult Create()
        {
            ViewData["ProvinceCode"] = new SelectList(_context.Province, "ProvinceCode", "ProvinceCode");
            return View();
        }

        // POST: BPDriver/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DriverId,City,DateHired,FirstName,FullName,HomePhone,LastName,PostalCode,ProvinceCode,Street,WorkPhone")] Driver driver)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(driver);
                    await _context.SaveChangesAsync();
                    TempData["message"] = "Driver successfully added";
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", $"Error adding a new driver: {ex.GetBaseException().Message}");
                }
                
            }
            ViewData["ProvinceCode"] = new SelectList(_context.Province, "ProvinceCode", "ProvinceCode", driver.ProvinceCode);
            return View(driver);
        }

        // GET: BPDriver/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var driver = await _context.Driver.SingleOrDefaultAsync(m => m.DriverId == id);
            if (driver == null)
            {
                return NotFound();
            }
            ViewData["ProvinceCode"] = new SelectList(_context.Province.OrderBy(d => d.Name), "ProvinceCode", "ProvinceCode", driver.ProvinceCode);
            TempData["fullName"] = driver.FullName;
            return View(driver);
        }

        // POST: BPDriver/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DriverId,City,DateHired,FirstName,FullName,HomePhone,LastName,PostalCode,ProvinceCode,Street,WorkPhone")] Driver driver)
        {
            if (id != driver.DriverId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(driver);
                    await _context.SaveChangesAsync();
                    TempData["message"] = "Driver details successfully changed";
                    return RedirectToAction("Index");
                }
                catch (DbUpdateConcurrencyException ex)
                {
                    if (!DriverExists(driver.DriverId))
                    {
                        //return NotFound();
                        ModelState.AddModelError("", $"Error editing the details of driver: {ex.GetBaseException().Message}");
                    }
                    else
                    { 
                        throw;
                    }
                }
                //TempData["successMessage"] = "Successfully changed details";
            }
            ViewData["ProvinceCode"] = new SelectList(_context.Province, "ProvinceCode", "ProvinceCode", driver.ProvinceCode);
            return View(driver);
        }

        // GET: BPDriver/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var driver = await _context.Driver.SingleOrDefaultAsync(m => m.DriverId == id);
            if (driver == null)
            {
                return NotFound();
            }

            return View(driver);
        }

        // POST: BPDriver/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var driver = await _context.Driver.SingleOrDefaultAsync(m => m.DriverId == id);
                _context.Driver.Remove(driver);
                await _context.SaveChangesAsync();
                TempData["message"] = "Driver successfully deleted";
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                TempData["message"] = ex.InnerException.Message;
            }
            return View("Index");
        }

        private bool DriverExists(int id)
        {
            return _context.Driver.Any(e => e.DriverId == id);
        }
    }
}

src/BPBusService/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
    <title>@ViewData["Title"] - BPBusService</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <img class="pull-left" height="50" width="50" src="~/images/bus.jpg" />
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">BPBusService</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="BPBusRoute" asp-action="Index">Bus Routes</a></li>
                    <li><a asp-area="" asp-controller="BPBusStop" asp-action="Index">Bus Stops</a></li>
                    <li><a asp-area="" asp-controller="BPDriver" asp-action="Index">Drivers</a></li>
                    @if (User.IsInRole("administrators"))
                    {
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Security</a>
                            <ul class="dropdown-menu">
                                <li><a asp-area="" asp-controller="BPUserMaintenance" asp-action="Index">User Maintenance</a></li>
                                <li><a asp-area="" asp-controller="BPRoleMaintenance" asp-action="Index">Role Maintenance</a></li>
                            </ul>
                        </li>
                    }
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        <strong><p class="text-danger">@TempData["message"]</p></strong>
        @RenderBody()

        <hr />
        <footer>
            <p>&copy; <a href="mailto:Bpatel0967@conestogac.on.ca"> Birju Patel</a>, Section 4</p>
            <ul class="nav navbar-nav navbar-right">
                <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
            </ul>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>

</html>